/**
 * Plays an `.iska` on the robot's ILI9341 panel (ESP32-S3), standalone.
 *
 *     pio run -t upload          # or, from the repository root: python tools/flash_esp32.py
 *     pio device monitor         # 115200 baud
 *
 * The asset is **embedded in the binary** (`board_build.embed_files`), so flashing
 * the firmware is enough: there is no LittleFS step and no file to upload.
 * `-DANIM_USE_LITTLEFS=1` reads `/rabbit3.iska` from LittleFS instead, when you want
 * to change the animation without recompiling.
 *
 * Behaviour -- the same as the SDL demo of the repository:
 *
 *   - the first looping animation plays forever (`idle_loop`);
 *   - `t` on the serial port plays the one-shot animation (`peek`) and goes back to
 *     the loop when it is over; `r` restarts the loop, `i` prints the asset summary;
 *   - `-DANIM_AUTO_MS=5000` replays the one-shot every 5 s, with no input at all.
 *
 * Only `Iska::Player` talks to the animation: the engine never learns about the
 * panel, the clock or the input. A touch screen would call `player.play("peek")`
 * and nothing else would change.
 */
#include <Arduino.h>

#include <cstdint>
#include <string>

#include "Iska/IskaLoader.h"
#include "Iska/IskaPlayer.h"

#include "display565.h"
#include "lcd_config.h"

#if ANIM_USE_LITTLEFS
#include <LittleFS.h>
#endif

// Symbols generated by `board_build.embed_files` (see platformio.ini): the .iska
// travels inside the firmware image.
extern "C" const uint8_t ISKA_BLOB_START[];
extern "C" const uint8_t ISKA_BLOB_END[];

namespace {

constexpr uint16_t    kBackground = 0x0000;   // black behind the sprites
constexpr const char* kOneShot    = "peek";   // played by `t` / by ANIM_AUTO_MS

Iska::Asset  asset;
Iska::Player player;
uint16_t*    frame      = nullptr;
const char*  idleName   = nullptr;
uint32_t     pushed     = 0;                  // frames since the last report
uint32_t     lastAuto   = 0;
uint32_t     lastReport = 0;
bool         ready      = false;

/** `/rabbit3.iska` from LittleFS, when the build asks for it. */
bool loadFromLittleFs() {
#if ANIM_USE_LITTLEFS
    if (!LittleFS.begin(true)) {
        Serial.println("[esp32] LittleFS could not be mounted");
        return false;
    }
    File file = LittleFS.open("/rabbit3.iska", "r");
    if (!file) {
        Serial.println("[esp32] /rabbit3.iska is not in LittleFS: using the embedded copy");
        return false;
    }
    const size_t size = file.size();
    uint8_t* blob = static_cast<uint8_t*>(ps_malloc(size));
    if (blob == nullptr) {
        Serial.printf("[esp32] no memory for the %u B of LittleFS\n",
                      static_cast<unsigned>(size));
        file.close();
        return false;
    }
    const size_t read = file.read(blob, size);
    file.close();
    std::string error;
    const bool ok = (read == size) && Iska::parseAsset(blob, size, asset, &error);
    free(blob);
    if (!ok) {
        Serial.printf("[esp32] the LittleFS asset was refused: %s\n", error.c_str());
        return false;
    }
    Serial.printf("[esp32] %.1f kB read from LittleFS\n", size / 1024.0);
    return true;
#else
    return false;
#endif
}

bool loadAsset() {
    if (loadFromLittleFs()) {
        return true;
    }
    const size_t size = static_cast<size_t>(ISKA_BLOB_END - ISKA_BLOB_START);
    std::string error;
    if (!Iska::parseAsset(ISKA_BLOB_START, size, asset, &error)) {
        Serial.printf("[esp32] the embedded asset was refused: %s\n", error.c_str());
        return false;
    }
    Serial.printf("[esp32] %.1f kB embedded in the firmware\n", size / 1024.0);
    return true;
}

/** The first looping animation is the background; the rest are one-shots. */
void pickIdle() {
    idleName = nullptr;
    for (const Iska::Animation& anim : asset.animations) {
        if (anim.loop) {
            idleName = anim.name.c_str();
            break;
        }
    }
    if (idleName == nullptr && !asset.animations.empty()) {
        idleName = asset.animations.front().name.c_str();
        Serial.println("[esp32] no looping animation: playing the first one");
    }
}

/** A touch, a button or `t`: the engine only needs the name. */
void triggerOneShot() {
    if (asset.find(kOneShot) == nullptr) {
        return;
    }
    if (player.play(kOneShot, true)) {
        Serial.printf("[esp32] %s\n", kOneShot);
    }
}

void readSerial() {
    while (Serial.available() > 0) {
        switch (Serial.read()) {
            case 't': case 'T': triggerOneShot(); break;
            case 'r': case 'R': player.play(idleName, true); break;
            case 'i': Serial.print(Iska::describe(asset).c_str()); break;
            default: break;
        }
    }
}

}  // namespace

void setup() {
    Serial.begin(115200);
    delay(150);
    Serial.println();
    Serial.println("[esp32] Intellar-Engine-Animation: ISKA on the ILI9341 panel");

    if (!loadAsset() || !player.bind(&asset)) {
        Serial.println("[esp32] FATAL: no usable asset");
        return;
    }
    Serial.print(Iska::describe(asset).c_str());

    const size_t bytes = static_cast<size_t>(asset.stageW) * asset.stageH * 2;
    frame = static_cast<uint16_t*>(ps_malloc(bytes));
    if (frame == nullptr) {
        frame = static_cast<uint16_t*>(malloc(bytes));
    }
    if (frame == nullptr) {
        Serial.printf("[esp32] FATAL: no memory for the %u B framebuffer\n",
                      static_cast<unsigned>(bytes));
        return;
    }
    if (!display565::begin()) {
        return;
    }

    pickIdle();
    player.play(idleName, true);
    ready = true;
    Serial.printf("[esp32] idle=%s (loop), one-shot=%s, %dx%d stage, %u B framebuffer\n",
                  idleName, kOneShot, asset.stageW, asset.stageH,
                  static_cast<unsigned>(bytes));
    Serial.println("[esp32] t = one-shot, r = restart the loop, i = asset summary");
}

void loop() {
    static uint32_t previous = 0;
    const uint32_t now = millis();
    const uint32_t delta = now - previous;
    previous = now;

    if (!ready) {
        delay(1000);
        return;
    }

    readSerial();
    player.update(delta);

    // a one-shot hands back to the loop as soon as it is over
    if (!player.looping() && player.finished()) {
        player.play(idleName, true);
    }

#if ANIM_AUTO_MS > 0
    if (player.looping() && now - lastAuto >= ANIM_AUTO_MS) {
        triggerOneShot();
        lastAuto = now;
    }
#endif

    player.render(frame, kBackground);
    display565::show(frame, player.stageWidth(), player.stageHeight());
    pushed++;

    if (now - lastReport >= 1000) {
        lastReport = now;
        const Iska::Animation* anim = player.animation();
        Serial.printf("[esp32] %2u fps, %s %u/%u ms%s (asset %.1f kB)\n",
                      static_cast<unsigned>(pushed), player.animationName(),
                      player.timeMs(), anim ? anim->durationMs : 0u,
                      player.looping() ? " loop" : "", asset.fileBytes / 1024.0);
        pushed = 0;
    }
    delay(1);      // leaves the radio and the rest of the system some air
}

